---
- name: Check passwdless login
  hosts: all
  gather_facts: False
  tasks:
        - name: check ssh to remote hosts works
          register: ssh_connection_test
          shell: "hostname; id"
          ignore_unreachable: yes
        - debug:
             msg: "Testing ssh_connection_test.stderr"
